# Makefile for CPE464 program 1

CC= gcc
CFLAGS= -g

# libraries are already in the link path.

all:   wreckingball

wreckingball: wreckingball.c
	$(CC) $(CFLAGS) wreckingball.c -c -lsox

clean:
	rm wreckingball



