/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"


//==============================================================================
/**
*/
class JbcfilterAudioProcessorEditor  : public AudioProcessorEditor, public SliderListener, public Timer
{
public:
    JbcfilterAudioProcessorEditor (JbcfilterAudioProcessor* ownerFilter);
    ~JbcfilterAudioProcessorEditor();

    //==============================================================================
    void paint (Graphics&) override;
    void timerCallback() override;
    void resized() override;
    void sliderValueChanged (Slider*) override;
    
private:
    Label infoLabel, tLabel, delayLabel, cutoffLabel;
    Slider delaySlider, cutoffSlider;
    ScopedPointer<ResizableCornerComponent> resizer;
    ComponentBoundsConstrainer resizeLimits;
    
    AudioPlayHead::CurrentPositionInfo lastDisplayedPosition;
    
    JbcfilterAudioProcessor *getProcessor() const
    {
        return static_cast <JbcfilterAudioProcessor*> (getAudioProcessor());
    }
    
    void displayPositionInfo (const AudioPlayHead::CurrentPositionInfo& pos);
    
};


#endif  // PLUGINEDITOR_H_INCLUDED
